#!/bin/env node
'use strict';

// Ping graphing tool:
// pingg google.com yahoo.com

const Config = require('bcfg');
const blessed = require('blessed');
const contrib = require('blessed-contrib');
const spawn = require('child_process').spawn;

// Parse arguments
const config = new Config('pingg', {
	alias: {
		'c': 'colors',
		// 'f': 'flood',
	},
});

config.inject({
	'colors': ['green', 'blue', 'red', 'white', 'yellow'],
});

config.load({ argv: true });
config.argv = config.argv.length && config.argv || ['8.8.8.8', '1.1.1.1'];
const colors = config.array('colors');
const data = [];
let cIndex = 0;

// Setup display
const screen = blessed.screen();
const line = contrib.line({
	xLabelPadding: 3,
	xPadding: 5,
	yLabelPadding: 1,
	yPadding: 1,
	showLegend: true,
	label: 'Network latency',
});
screen.append(line);
screen.key(['escape', 'q', 'C-c'], function(ch, key) {
	return process.exit(0);
});
screen.render();

// Ping each host and display results
for (const host of config.argv) {
	const ping = spawn('ping', [host]);
	const hostData = {
		title: host,
		x:[],
		y:[],
		style: {
			line: colors[cIndex++ % colors.length],
		},
	};
	data.push(hostData);

	ping.stdout.on('data', function(d) {
		// console.log("DATA!!!", d.toString())
		const latency = (/time=([\d\.]+) ms/g).exec(d.toString());
		if (latency) {
			hostData.x.push((new Date()).toLocaleTimeString());
			hostData.y.push(parseFloat(latency[1]));
			line.setData(data);
			screen.render();
		}
	});

	ping.stdout.on('end', function() {
		hostData.title = '!! ' + host
	});
}
